fix: Stringify journal entry path
Pass a `pathlib.Path` Object to `click.edit()` was causing:

```python
TypeError: expected string or bytes-like object
```